INSERT INTO FUNCIONARIO
(MATRICULA, SENHA, NOME, GESTOR)
VALUES
('1001','123','Hudson Sena',FALSE);

INSERT INTO FUNCIONARIO
(MATRICULA, SENHA, NOME, GESTOR)
VALUES
('2001','123','Gestor Sistema',TRUE);

INSERT INTO GESTOR (ID)
VALUES (2);