CREATE TABLE FUNCIONARIO (

    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA VARCHAR(20) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    GESTOR BOOLEAN NOT NULL

);

CREATE TABLE GESTOR (

    ID BIGINT PRIMARY KEY,

    CONSTRAINT FK_GESTOR_FUNCIONARIO
        FOREIGN KEY (ID)
        REFERENCES FUNCIONARIO(ID)

);

CREATE TABLE REGISTRO_PONTO (

    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    FUNCIONARIO_ID BIGINT NOT NULL,
    HORARIO TIMESTAMP NOT NULL,
    TIPO VARCHAR(30) NOT NULL,

    CONSTRAINT FK_REGISTRO_FUNCIONARIO
        FOREIGN KEY (FUNCIONARIO_ID)
        REFERENCES FUNCIONARIO(ID)

);